@ElsaProServer_HostAddress = http://localhost:8080

GET {{ElsaProServer_HostAddress}}/health
Accept: application/json

###

GET {{ElsaProServer_HostAddress}}/sample-endpoint
Accept: application/json

###
