@ElsaProServer_HostAddress = https://localhost:7292

GET {{ElsaProServer_HostAddress}}/health
Accept: application/json

###

GET {{ElsaProServer_HostAddress}}/sample-endpoint
Accept: application/json

###
