@ElsaProServer_HostAddress = https://localhost:5001

GET {{ElsaProServer_HostAddress}}/health
Accept: application/json

###

GET {{ElsaProServer_HostAddress}}/sample-endpoint
Accept: application/json

###
